Fix ps: 'improper AIX field descriptor'
It appears that `ps` doesn't support using custom separators (e.g. here: '|') on all OSes. This replaces it with hardcoded lengths when known (cpu, mem, etc...).

E.G. on a debian bookworm machine this is what it returns:
```
ps -eo '%p|%c|%C|' -o "%mem" -o '|%a' --sort=-%cpu
error: improper AIX field descriptor
```